version: '3'
services:
  db:
    container_name: c_db
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=test1
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3333:3306"
volumes:
  data:
