const ADD_RECORD = 'ADD_RECORD'
const EDIT_RECORD = 'EDIT_RECORD'
const DELETE_RECORD = 'DELETE_RECORD'
const COPY_TABLE = 'COPY_TABLE'
const DELETE_TABLE = 'DELETE_TABLE'

export {
    ADD_RECORD,
    EDIT_RECORD,
    DELETE_RECORD,
    COPY_TABLE,
    DELETE_TABLE,
}
