const ADD_TODO = "ADD_TODO";
const TOGGLE_TODO = "TOGGLE_TODO";
const SET_FILTER = "SET_FILTER";

const ADD_RECORDS = 'ADD_RECORDS'
const EDIT_RECORDS = 'EDIT_RECORDS'
const DELETE_RECORDS = 'DELETE_RECORDS'

const COPY_TABLE = 'COPY_TABLE'

export {
    ADD_TODO,
    TOGGLE_TODO,
    SET_FILTER,

    // new
    ADD_RECORDS,
    EDIT_RECORDS,
    DELETE_RECORDS,
    COPY_TABLE
}
